CREATE TABLE [dbo].[game] (
    [id]                                  TINYINT        IDENTITY (1, 1) NOT NULL,
    [scoring_ea_index]                    TINYINT        NOT NULL,
    [league_prefix_public]                VARCHAR (50)   NOT NULL,
    [bps_tackles]                         TINYINT        NOT NULL,
    [league_h2h_tiebreak]                 VARCHAR (50)   NOT NULL,
    [scoring_long_play]                   TINYINT        NOT NULL,
    [bps_recoveries_limit]                TINYINT        NOT NULL,
    [facebook_app_id]                     VARCHAR (50)   NOT NULL,
    [bps_tackled]                         TINYINT        NOT NULL,
    [bps_errors_leading_to_goal]          TINYINT        NOT NULL,
    [bps_yellow_cards]                    TINYINT        NOT NULL,
    [ui_el_hide_currency_qi]              BIT            NOT NULL,
    [scoring_bonus]                       TINYINT        NOT NULL,
    [transfers_cost]                      TINYINT        NOT NULL,
    [bps_long_play]                       TINYINT        NOT NULL,
    [bps_long_play_limit]                 INT            NOT NULL,
    [scoring_assists]                     TINYINT        NOT NULL,
    [scoring_long_play_limit]             TINYINT        NOT NULL,
    [fifa_league_id]                      INT            NOT NULL,
    [league_size_classic_max]             TINYINT        NOT NULL,
    [scoring_red_cards]                   TINYINT        NOT NULL,
    [scoring_creativity]                  TINYINT        NOT NULL,
    [game_timezone]                       VARCHAR (50)   NOT NULL,
    [static_game_url]                     VARCHAR (100)  NOT NULL,
    [currency_symbol]                     VARCHAR (10)   NOT NULL,
    [bps_target_missed]                   TINYINT        NOT NULL,
    [bps_penalties_saved]                 TINYINT        NOT NULL,
    [support_email_address]               VARCHAR (50)   NOT NULL,
    [cup_start_event_id]                  TINYINT        NOT NULL,
    [scoring_penalties_saved]             TINYINT        NOT NULL,
    [scoring_threat]                      TINYINT        NOT NULL,
    [scoring_saves]                       TINYINT        NOT NULL,
    [league_join_private_max]             TINYINT        NOT NULL,
    [scoring_short_play]                  TINYINT        NOT NULL,
    [sys_use_event_live_api]              BIT            NOT NULL,
    [scoring_concede_limit]               TINYINT        NOT NULL,
    [bps_key_passes]                      TINYINT        NOT NULL,
    [bps_clearances_blocks_interceptions] TINYINT        NOT NULL,
    [bps_pass_percentage_90]              TINYINT        NOT NULL,
    [bps_big_chances_missed]              TINYINT        NOT NULL,
    [league_max_ko_rounds_h2h]            TINYINT        NOT NULL,
    [bps_open_play_crosses]               TINYINT        NOT NULL,
    [league_points_h2h_win]               TINYINT        NOT NULL,
    [bps_saves]                           TINYINT        NOT NULL,
    [bps_cbi_limit]                       TINYINT        NOT NULL,
    [league_size_h2h_max]                 TINYINT        NOT NULL,
    [sys_vice_captain_enabled]            BIT            NOT NULL,
    [squad_squadplay]                     TINYINT        NOT NULL,
    [bps_fouls]                           TINYINT        NOT NULL,
    [squad_squadsize]                     TINYINT        NOT NULL,
    [ui_selection_short_team_names]       BIT            NOT NULL,
    [transfers_sell_on_fee]               DECIMAL (5, 2) NOT NULL,
    [transfers_type]                      VARCHAR (10)   NOT NULL,
    [scoring_ict_index]                   TINYINT        NOT NULL,
    [bps_pass_percentage_80]              TINYINT        NOT NULL,
    [bps_own_goals]                       TINYINT        NOT NULL,
    [scoring_yellow_cards]                TINYINT        NOT NULL,
    [bps_pass_percentage_70]              TINYINT        NOT NULL,
    [ui_show_home_away]                   BIT            NOT NULL,
    [ui_el_hide_currency_sy]              BIT            NOT NULL,
    [bps_assists]                         TINYINT        NOT NULL,
    [squad_team_limit]                    TINYINT        NOT NULL,
    [league_points_h2h_draw]              TINYINT        NOT NULL,
    [transfers_limit]                     TINYINT        NOT NULL,
    [bps_dribbles]                        TINYINT        NOT NULL,
    [perform_league_id]                   INT            NOT NULL,
    [bps_offside]                         TINYINT        NOT NULL,
    [sys_cdn_cache_enabled]               BIT            NOT NULL,
    [currency_multiplier]                 TINYINT        NOT NULL,
    [bps_red_cards]                       TINYINT        NOT NULL,
    [bps_winning_goals]                   TINYINT        NOT NULL,
    [league_join_public_max]              TINYINT        NOT NULL,
    [league_points_h2h_lose]              TINYINT        NOT NULL,
    [currency_decimal_places]             TINYINT        NOT NULL,
    [bps_errors_leading_to_goal_attempt]  TINYINT        NOT NULL,
    [ui_selection_price_gap]              TINYINT        NOT NULL,
    [bps_big_chances_created]             TINYINT        NOT NULL,
    [ui_selection_player_limit]           TINYINT        NOT NULL,
    [bps_attempted_passes_limit]          TINYINT        NOT NULL,
    [scoring_penalties_missed]            TINYINT        NOT NULL,
    [photo_base_url]                      VARCHAR (100)  NOT NULL,
    [scoring_bps]                         TINYINT        NOT NULL,
    [scoring_influence]                   TINYINT        NOT NULL,
    [bps_penalties_conceded]              TINYINT        NOT NULL,
    [scoring_own_goals]                   TINYINT        NOT NULL,
    [squad_total_spend]                   TINYINT        NOT NULL,
    [bps_short_play]                      TINYINT        NOT NULL,
    [ui_element_wrap]                     TINYINT        NOT NULL,
    [bps_recoveries]                      TINYINT        NOT NULL,
    [bps_penalties_missed]                TINYINT        NOT NULL,
    [scoring_saves_limit]                 TINYINT        NOT NULL,
    CONSTRAINT [PK_game] PRIMARY KEY CLUSTERED ([id] ASC)
);

