CREATE TABLE [dbo].[history_summary] (
    [id]                              INT           NOT NULL,
    [kickoff_time]                    SMALLDATETIME NOT NULL,
    [kickoff_time_formatted]          VARCHAR (16)  NULL,
    [team_h_score]                    TINYINT       NULL,
    [team_a_score]                    TINYINT       NULL,
    [was_home]                        BIT           NOT NULL,
    [gameweekId]                      INT			NOT NULL,
    [total_points]                    INT           NOT NULL,
    [value]                           INT           NOT NULL,
    [transfers_balance]               INT           NOT NULL,
    [selected]                        INT           NOT NULL,
    [transfers_in]                    INT           NOT NULL,
    [transfers_out]                   INT           NOT NULL,
    [loaned_in]                       INT           NOT NULL,
    [loaned_out]                      INT           NOT NULL,
    [minutes]                         INT           NOT NULL,
    [goals_scored]                    INT           NOT NULL,
    [assists]                         INT           NOT NULL,
    [clean_sheets]                    INT           NOT NULL,
    [goals_conceded]                  INT           NOT NULL,
    [own_goals]                       INT           NOT NULL,
    [penalties_saved]                 INT           NOT NULL,
    [penalties_missed]                INT           NOT NULL,
    [yellow_cards]                    INT           NOT NULL,
    [red_cards]                       INT           NOT NULL,
    [saves]                           INT           NOT NULL,
    [bonus]                           INT           NOT NULL,
    [bps]                             INT           NOT NULL,
    [influence]                       VARCHAR (50)  NOT NULL,
    [creativity]                      VARCHAR (50)  NOT NULL,
    [threat]                          VARCHAR (50)  NOT NULL,
    [ict_index]                       VARCHAR (50)  NOT NULL,
    [ea_index]                        INT           NOT NULL,
    [open_play_crosses]               INT           NOT NULL,
    [big_chances_created]             INT           NOT NULL,
    [clearances_blocks_interceptions] INT           NOT NULL,
    [recoveries]                      INT           NOT NULL,
    [key_passes]                      INT           NOT NULL,
    [tackles]                         INT           NOT NULL,
    [winning_goals]                   INT           NOT NULL,
    [attempted_passes]                INT           NOT NULL,
    [completed_passes]                INT           NOT NULL,
    [penalties_conceded]              INT           NOT NULL,
    [big_chances_missed]              INT           NOT NULL,
    [errors_leading_to_goal]          INT           NOT NULL,
    [errors_leading_to_goal_attempt]  INT           NOT NULL,
    [tackled]                         INT           NOT NULL,
    [offside]                         INT           NOT NULL,
    [target_missed]                   INT           NOT NULL,
    [fouls]                           INT           NOT NULL,
    [dribbles]                        INT           NOT NULL,
    [element]                         INT           NOT NULL,
    [fixture]                         INT           NOT NULL,
    [opponent_team]                   INT           NOT NULL,
    CONSTRAINT [PK_history_summary] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_history_summary_gameweekId] FOREIGN KEY ([gameweekId]) REFERENCES [dbo].[Gameweeks] ([id])
);

