CREATE TABLE dbo.UserTeamCounts
(
	Id INT IDENTITY(1,1) NOT NULL,
	UserTableName VARCHAR(100) NOT NULL,
	UserTeamCount INT NOT NULL,
	CountDate DATETIME NOT NULL,
	CONSTRAINT PK_UserTeamCounts PRIMARY KEY CLUSTERED (Id ASC)
);