CREATE TABLE [dbo].[FactPlayerCurrentStats]
(
	PlayerCurrentStatsKey INT IDENTITY(1,1) NOT NULL,
	PlayerKey INT NOT NULL,
	Cost TINYINT NOT NULL,
	SelectedByPercent DECIMAL (6,2) NOT NULL,
	Form DECIMAL (6,2) NOT NULL,
    TotalPoints SMALLINT NOT NULL,
    EventPoints SMALLINT NOT NULL,
    PointsPerGame DECIMAL (4, 2) NOT NULL,
	TransferInTotal INT NOT NULL,
	TransferOutTotal INT NOT NULL,
	TransferIn INT NOT NULL,
	TransferOut INT NOT NULL,
    MinutesTotal SMALLINT NOT NULL,
    GoalsScored TINYINT NOT NULL,
    Assists TINYINT NOT NULL,
    CleanSheets TINYINT NOT NULL,
    GoalsConceded TINYINT NOT NULL,
    OwnGoals TINYINT NOT NULL,
    PenaltiesSaved TINYINT NOT NULL,
    PenaltiesMissed TINYINT NOT NULL,
    YellowCards TINYINT NOT NULL,
    RedCards TINYINT NOT NULL,
    Saves TINYINT NOT NULL,
    Bonus TINYINT NOT NULL,
	CONSTRAINT [PK_FactPlayerCurrentStats] PRIMARY KEY CLUSTERED (PlayerCurrentStatsKey ASC),
	CONSTRAINT [FK_FactPlayerCurrentStats_PlayerKey] FOREIGN KEY (PlayerKey) REFERENCES [dbo].[DimPlayer] ([PlayerKey])
);