CREATE TABLE [dbo].[FactHistoryPast]
(
	[Id]			   INT			  NOT NULL,
	[PlayerId]         INT            NOT NULL,
	[SeasonId]         INT			  NOT NULL,
    [ElementCode]      INT            NOT NULL,
    [StartCost]        TINYINT        NOT NULL,
    [EndCost]          TINYINT        NOT NULL,
    [TotalPoints]      SMALLINT       NOT NULL,
    [Minutes]          SMALLINT       NOT NULL,
    [GoalsScored]      TINYINT        NOT NULL,
    [Assists]          TINYINT        NOT NULL,
    [CleanSheets]      TINYINT        NOT NULL,
    [GoalsConceded]    TINYINT        NOT NULL,
    [OwnGoals]         TINYINT        NOT NULL,
    [PenaltiesSaved]   TINYINT        NOT NULL,
    [PenaltiesMissed]  TINYINT        NOT NULL,
    [YellowCards]      TINYINT        NOT NULL,
    [RedCards]         TINYINT        NOT NULL,
    [Saves]            TINYINT        NOT NULL,
    [Bonus]            TINYINT        NOT NULL,
    [BPS]              SMALLINT       NOT NULL,
    [Influence]        DECIMAL (6, 2) NOT NULL,
    [Creativity]       DECIMAL (6, 2) NOT NULL,
    [Threat]           DECIMAL (6, 2) NOT NULL,
    [ICTIndex]         DECIMAL (6, 2) NOT NULL,
    [EAIndex]          SMALLINT       NOT NULL,
    CONSTRAINT [PK_HistoryPast] PRIMARY KEY CLUSTERED ([id] ASC),
	CONSTRAINT [FK_HistoryPast_PlayerId] FOREIGN KEY ([PlayerId]) REFERENCES [dbo].[DimPlayer] ([PlayerId]),
	CONSTRAINT [FK_HistoryPast_SeasonId] FOREIGN KEY ([SeasonId]) REFERENCES [dbo].[DimSeason] ([SeasonId])
);