CREATE TABLE [dbo].[FactPlayerDailyAttributes]
(
	PlayerKey                    INT NOT NULL,
	DateKey                      INT NOT NULL,
	ChanceOfPlayingThisRound     DECIMAL(5,2) NULL,
	ChanceOfPlayingNextRound     DECIMAL(5,2) NULL,
    ValueForm                    DECIMAL (6,2)  NOT NULL,
    ValueSeason                  DECIMAL (6,2)  NOT NULL,
    CostChangeStart              SMALLINT       NOT NULL,
    CostChangeEvent              SMALLINT       NOT NULL,
    CostChangeStartFall          SMALLINT       NOT NULL,
    CostChangeEventFall          SMALLINT       NOT NULL,
    InDreamteam                  BIT            NOT NULL,
    DreamteamCount               TINYINT        NOT NULL,
    SelectedByPercent            DECIMAL(6,2) NOT NULL,
    Form                         DECIMAL(6,2) NULL,
    TransfersOut                 INT NOT NULL,
    TransfersIn                  INT NOT NULL,
    TransfersOutEvent            INT NOT NULL,
    TransfersInEvent             INT NOT NULL,
    LoansIn                      TINYINT NOT NULL,
    LoansOut                     TINYINT NOT NULL,
    LoanedIn                     TINYINT NOT NULL,
    LoanedOut                    TINYINT NOT NULL,
    TotalPoints                  SMALLINT NOT NULL,
    EventPoints                  SMALLINT NOT NULL,
    PointsPerGame                DECIMAL(4,2) NOT NULL,
    ExpectedPointsThis           DECIMAL(4,2) NULL,
    ExpectedPointsNext           DECIMAL(4,2) NULL,
	Influence                    DECIMAL (6,2) NULL,
    Creativity                   DECIMAL (6,2) NULL,
    Threat                       DECIMAL (6,2) NULL,
    ICT_Index                    DECIMAL (6,2) NULL,
    EA_Index                     SMALLINT NOT NULL,
	CONSTRAINT PK_FactPlayerDailyAttributes PRIMARY KEY CLUSTERED (PlayerKey ASC,DateKey ASC),
    CONSTRAINT [FK_FactPlayerDailyAttributes_DateKey] FOREIGN KEY ([DateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
	CONSTRAINT FK_FactPlayerDailyAttributes_PlayerKey FOREIGN KEY(PlayerKey) REFERENCES dbo.DimPlayer ([PlayerKey])
);