CREATE TABLE dbo.WeightingFactorsAnalysis
(
	SeasonKey INT,
	GameweekStartKey INT,
	Gameweeks INT,
	PlayerPositionKey INT,
	PredictionPointsAllWeighting INT,
	PredictionPoints5Weighting INT,
	PredictionPoints10Weighting INT,
	PlayerKey INT,
	PlayerName VARCHAR(100),
	Cost INT,
	PlayerPosition VARCHAR(3),
	TeamName VARCHAR(50),
	TotalPlayerGames INT,
	TotalPlayerMinutes INT,
	CurrentPoints INT,
	PredictedPointsAll DECIMAL(6,2),
	PredictedPoints5 DECIMAL(6,2),
	PredictedPoints10 DECIMAL(6,2),
	OverallPPGPredictionPoints DECIMAL(10,6),
	OverallTeamPPGPredictionPoints DECIMAL(10,6),
	OverallDifficultyPPGPredictionPoints DECIMAL(10,6),
	OverallFractionOfMinutesPlayed DECIMAL(10,6),
	Prev5FractionOfMinutesPlayed DECIMAL(10,6),
	StartingProbability DECIMAL(10,6),
	TotalGames INT,
	TeamTotalGames INT,
	DifficultyTotalGames INT,
	PredictedPointsPath INT,
	PredictedPoints DECIMAL(10,6),
	PredictedPointsWeighted DECIMAL(10,6),
	ChanceOfPlayingNextRound DECIMAL(6,2),
	CONSTRAINT [PK_WeightingFactorsAnalysis] PRIMARY KEY CLUSTERED (PlayerKey ASC, SeasonKey ASC, GameweekStartKey ASC, Gameweeks ASC, PredictionPointsAllWeighting ASC, PredictionPoints5Weighting ASC, PredictionPoints10Weighting ASC)
);