CREATE TABLE dbo.DimChip
(
	ChipKey INT IDENTITY(1,1) NOT NULL,
	ChipName VARCHAR(28) NOT NULL,
	ChipDescription VARCHAR(28) NOT NULL,
	ChipId INT NOT NULL,
	SeasonKey INT NOT NULL,
	CONSTRAINT PK_DimChip PRIMARY KEY CLUSTERED (ChipKey ASC)
)
GO